markdown: rdiscount 
permalink: /:year/:month/:day/:title 
title: Hu
url: 
subscribe: 
exclude: [ README.md, newpost.rb ]
domain: 
author: Longzhong Hu
email: 76212193@qq.com
auto: true
twitterID: 
googleAnalyticsID: 
disqusShortname: 